import type { Blueprint } from "@/types/output";
import type { Project } from "@/types/project";

export function exportMarkdown(project: Project, blueprint: Blueprint): string {
  const b = blueprint;
  const lines: string[] = [];

  lines.push(`# ${b.productBrief.projectName || project.title}`, "");
  lines.push(`> ${b.productBrief.oneLiner}`, "");
  lines.push("## Build Plan", b.orchestrationPlan.summary, "");
  lines.push("### Guardrails");
  b.orchestrationPlan.guardrails.forEach((g) => lines.push(`- ${g}`));
  lines.push("");

  lines.push("## Problem", b.productBrief.problem, "");
  lines.push(
    "## Target Users",
    ...b.productBrief.targetUsers.map((u) => `- ${u}`),
    "",
  );
  lines.push("## Value Proposition", b.productBrief.mainValue, "");

  lines.push("## Market Analysis");
  lines.push("### Competitors");
  b.marketAnalysis.competitors.forEach((c) => lines.push(`- ${c}`));
  lines.push("### Positioning", b.marketAnalysis.positioning);
  lines.push("### Differentiation");
  b.marketAnalysis.differentiation.forEach((d) => lines.push(`- ${d}`));
  lines.push("");

  lines.push("## MVP Scope");
  lines.push("### Must have");
  b.mvpScope.mustHave.forEach((f) => lines.push(`- **${f.feature}** — ${f.why}`));
  lines.push("### Nice to have");
  b.mvpScope.niceToHave.forEach((f) =>
    lines.push(`- **${f.feature}** — ${f.whyLater}`),
  );
  lines.push("### Out of scope");
  b.mvpScope.outOfScope.forEach((f) =>
    lines.push(`- **${f.feature}** — ${f.reason}`),
  );
  lines.push("");

  lines.push("## UX Flow", b.uxFlow.journey, "");
  lines.push("### Screens");
  b.uxFlow.screens.forEach((s) =>
    lines.push(`- **${s.name}** — ${s.purpose} (action: ${s.primaryAction})`),
  );
  lines.push("");

  lines.push("## Tech Architecture", b.techPlan.architecture, "");
  lines.push("### Stack");
  const stack = b.techPlan.recommendedStack ?? {};
  Object.entries(stack).forEach(([k, v]) => lines.push(`- ${k}: ${v}`));
  lines.push("### Database tables");
  b.techPlan.databaseTables.forEach((t) => lines.push(`- ${t}`));
  lines.push("### API routes");
  b.techPlan.apiRoutes.forEach((r) => lines.push(`- ${r}`));
  lines.push("");

  lines.push("## Code Skeleton");
  b.codeSkeleton.fileTree.forEach((file) =>
    lines.push(`- \`${file.path}\` — ${file.purpose}`),
  );
  lines.push("### Starter tasks");
  b.codeSkeleton.starterTasks.forEach((task) => lines.push(`- ${task}`));
  lines.push("");

  lines.push("## Product Backlog");
  b.backlog.items.forEach((i) =>
    lines.push(
      `- [${i.priority}] ${i.title} (Sprint ${i.sprint}) — ${i.userStory}`,
    ),
  );
  lines.push("");

  lines.push("## Sprint Plan");
  b.sprintPlan.sprints.forEach((s) => {
    lines.push(`### ${s.name} — ${s.goal}`);
    s.items.forEach((i) => lines.push(`- ${i}`));
  });
  lines.push("");

  lines.push("## Test Plan");
  lines.push("### Happy path");
  b.testPlan.happyPath.forEach((t) => lines.push(`- ${t.name}`));
  lines.push("### Edge cases");
  b.testPlan.edgeCases.forEach((t) => lines.push(`- ${t.name}`));
  lines.push("### Demo checklist");
  b.testPlan.demoChecklist.forEach((c) => lines.push(`- [ ] ${c}`));
  lines.push("");

  lines.push("---", "_Generated by BuildPixies — your tiny AI product team._");

  return lines.join("\n");
}
