import type { CreateProjectInput } from "@/types/project";
import type { Blueprint, BlueprintSection } from "@/types/output";
import { productPixie } from "@/lib/ai/pixies/product";
import { uxPixie } from "@/lib/ai/pixies/ux";
import { techPixie } from "@/lib/ai/pixies/tech";
import { qaPixie } from "@/lib/ai/pixies/qa";
import { scrumPixie } from "@/lib/ai/pixies/scrum";
import { isOpenAIConfigured, runJsonCompletion } from "@/lib/ai/client";
import { buildSampleBlueprint } from "@/lib/ai/sample";
import { validateSection } from "@/lib/ai/schemas";
import { docsPrompt } from "@/lib/ai/prompts";

export interface OrchestratorEvent {
  pixie: string;
  section: BlueprintSection;
  status: "thinking" | "done" | "failed";
}

export type OrchestratorListener = (event: OrchestratorEvent) => void;

const pipeline = [productPixie, uxPixie, techPixie, qaPixie, scrumPixie] as const;

export async function generateBlueprint(
  input: CreateProjectInput,
  onEvent?: OrchestratorListener,
): Promise<Blueprint> {
  if (!isOpenAIConfigured()) {
    const sample = buildSampleBlueprint(input.rawIdea);
    pipeline.forEach((pixie) =>
      onEvent?.({ pixie: pixie.name, section: pixie.section, status: "done" }),
    );
    return sample;
  }

  const outputs: Partial<Record<BlueprintSection, unknown>> = {};
  const ctx = { input, previousOutputs: outputs };

  for (const pixie of pipeline) {
    onEvent?.({ pixie: pixie.name, section: pixie.section, status: "thinking" });
    try {
      const { system, user } = pixie.build(ctx);
      const data = await runJsonCompletion(system, user);
      const parsed = validateSection(pixie.section, data);
      outputs[pixie.section] = parsed.success ? parsed.data : data;
      onEvent?.({ pixie: pixie.name, section: pixie.section, status: "done" });
    } catch (error) {
      onEvent?.({ pixie: pixie.name, section: pixie.section, status: "failed" });
      throw error;
    }
  }

  let readme = "";
  try {
    const { system, user } = docsPrompt(ctx);
    readme = String(await runJsonCompletion(system, user));
  } catch {
    readme = `# ${input.rawIdea.slice(0, 60)}\n\nGenerated by BuildPixies.`;
  }

  return { ...outputs, readme } as unknown as Blueprint;
}

export async function regenerateSection(
  input: CreateProjectInput,
  section: BlueprintSection,
  previousOutputs?: Record<string, unknown>,
): Promise<unknown> {
  if (!isOpenAIConfigured()) {
    return buildSampleBlueprint(input.rawIdea)[section];
  }
  const builders: Record<string, () => { system: string; user: string }> = {
    productBrief: () => productPixie.build({ input, previousOutputs }),
    uxFlow: () => uxPixie.build({ input, previousOutputs }),
    techPlan: () => techPixie.build({ input, previousOutputs }),
    testPlan: () => qaPixie.build({ input, previousOutputs }),
    sprintPlan: () => scrumPixie.build({ input, previousOutputs }),
  };
  const builder = builders[section];
  if (!builder) throw new Error(`Cannot regenerate section: ${section}`);
  const { system, user } = builder();
  return runJsonCompletion(system, user);
}
